---
name: Geo-LocaPoint
version: 0.0.4
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
abstract: Simple encoder/decoder of LocaPoint
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Math::Round: 0
  Test::Base: 0
  version: 0
provides:
  Geo::Formatter::Format::LocaPoint:
    file: lib/Geo/Formatter/Format/LocaPoint.pm
    version: 0.0.4
  Geo::LocaPoint:
    file: lib/Geo/LocaPoint.pm
    version: 0.0.4
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
